Create Docker Image using Gradescope format
ucbds-infra/otter-grader pull request #127
Opened 2020-10-02 22:27 UTC by edwardlhwang

To test containers.py:

1. Uncomment out lines 18-19, 363-365
2. Run:  
```
cd otter-grader
python3 otter/grade/containers.py
```

2020-10-05 03:00 UTC, chrispyles requested changes

2020-10-05 04:11 UTC, edwardlhwang commented on otter/grade/containers.py
> +        ["docker", "build","--build-arg", "ZIPPATH=" + zip_path, ".", "-f", "otter/grade/Dockerfile", "-t", tag],
are these two links supposed to be the same?

2020-10-06 18:14 UTC, chrispyles commented on otter/grade/containers.py
> +        ["docker", "build","--build-arg", "ZIPPATH=" + zip_path, ".", "-f", "otter/grade/Dockerfile", "-t", tag],
F

2020-10-06 18:14 UTC, chrispyles commented on otter/grade/containers.py
> +        ["docker", "build","--build-arg", "ZIPPATH=" + zip_path, ".", "-f", "otter/grade/Dockerfile", "-t", tag],
https://github.com/ucbds-infra/otter-grader/blob/master/setup.py#L33

2020-10-21 20:04 UTC, chrispyles approved these changes

2020-11-20 01:17 UTC, merged