Add support for working with a remote docker host
ucbds-infra/otter-grader pull request #582
Opened 2022-11-15 12:33 UTC by nibheis

These (simple) changes make it possible to run the docker grading container on a remote host.

2022-11-16 01:03 UTC, chrispyles requested changes

2022-11-16 01:03 UTC, chrispyles commented on otter/grade/containers.py
> +        docker.container.start(container, **args)
I think you can remove `**args` from here -- `start` only has 2 kwargs, neither of which are set here.

2022-11-16 07:21 UTC, nibheis commented
I pushed the requested changes to my repo. Let me know how I can help.

2022-11-17 03:20 UTC, chrispyles approved these changes

2022-11-20 04:51 UTC, merged