Fix #686 (Grader Export Cell Fails)
ucbds-infra/otter-grader pull request #687
Opened 2023-08-01 06:25 UTC by bdsomer

This PR fixes #686. It feels kind of hacky, so I'm not sure if it's the correct way to fix the issue. I also tried passing the `-Xfrozen_modules=off` argument, but this doesn't solve the issue. Instead, the `stderr` output of the process changes from

```
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
```

to

```
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
```

I presume that the subprocess starts *another* subprocess (without using the `-Xfrozen_modules=off` flag) which triggers the successive warning. By starting the former subprocess with the `PYDEVD_DISABLE_FILE_VALIDATION=1` environment variable, the latter subprocess inherits it and suppresses the second warning.

2023-08-03 00:45 UTC, chrispyles requested changes
Thanks for the PR! Please add an entry to the changelog noting this change and the issue it fixes.

2023-08-03 02:14 UTC, bdsomer commented
@chrispyles There is currently no new version for me to list changes for---what should I title the upcoming release? I assume I should also put `(unreleased)` in the title, based on previous PRs.

2023-08-04 03:03 UTC, chrispyles commented
@bdsomer actually can you change the base of this PR to the beta branch? This will be part of v5.1.0 which is currently being built there and it already has a changelog entry started.

2023-08-05 19:19 UTC, chrispyles commented
Hi @bdsomer, v5.1.0 is nearly ready for release (probably going to go out in a couple of days). If this PR isn't in before then then I can push it in a patch release (v5.1.x).

2023-08-06 02:34 UTC, bdsomer commented
#691 merges into `beta` and updates `CHANGELOG.md`, as requested

2023-08-06 02:34 UTC, closed without merging